name: Github CI Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies via Composer
        run: COMPOSER_NO_DEV=0 composer install

      - name: CS-Fixer dry-run
        run: php vendor/bin/php-cs-fixer fix --dry-run    

      - name: Deptrac analyse
        run: vendor/bin/deptrac analyse

      - name: Yamllint
        run: yamllint .
        
      - name: PHPStan analyse
        run: php vendor/bin/phpstan analyse -c phpstan.neon        

  tests:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_PASSWORD: '!ChangeMe!'
          POSTGRES_DB: app
          POSTGRES_USER: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
        ports:
          - 5432:5432    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies via Composer
        run: COMPOSER_NO_DEV=0 composer install

      - name: Drop test db if exists
        run: php bin/console doctrine:database:drop --if-exists --env=test --force -n

      - name: Create test db
        run: bin/console doctrine:database:create --env=test -n

      - name: Run migrations
        run: bin/console doctrine:migrations:migrate --env=test --quiet -n

      - name: Run PHPUnit with coverage and print report
        run: |
          mkdir -p coverage
          php vendor/bin/phpunit tests --coverage-text

      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-report
      #     path: coverage/clover.xml

